config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'

  }


  get 'sample/index'

  get 'sample/create'

  get 'sample/new'

  get 'issue_comment/index'

  get 'issue_comment/edit'

  get 'issue_comment/create'

  get 'issue_comment/add'

  get 'issue/index'

  get 'issue/create'

  get 'issue/new'

  get 'issue/edit'

  get 'outlet/index'

  get 'outlet/new'


  post 'outlet/create'

  get 'outlet/destroy'

  get 'outlet/edit'

  get 'balance/index'
  get 'balance', to: 'balance#index'
  get 'issues', to: 'issue#index'
  get 'issue/:id', to: 'issue#show'
  get 'comments', to: 'comment#index'
  get 'comment/new'
  get 'comment/create'
  post 'comment/create', to: 'comment#create'
  get 'samples', to: 'sample#index'
  post 'sample/create', to: 'sample#create'

  post 'issue/create', to: 'issue#create'
  post 'issue/add', to: 'issue#add'

  get 'balance/create'

  get 'balance/new'

  namespace :admin do
    get 'client/new'
  end

  namespace :admin do
    get 'client/show'
  end

  namespace :admin do
    get 'client/create'
  end

  namespace :admin do
    get 'client/update'
  end

  namespace :admin do
    get 'client/edit'
  end

  namespace :admin do
    get 'client/index'
  end



  root 'static#index'

  get 'static/index'

  get 'static/about'

  get 'static/contact'

  resource :cities
  namespace :admin do
    root 'static#index'

    get 'clients', to: 'client#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one :outlet, :primary_key => :outlet_id, :foreign_key => :id
  validates :text, :presence=> true
end

app/models/issue.rb
class Issue < ApplicationRecord

  validates :title, :presence=> true
  validates :text, :presence=> true
  has_one :outlet, :primary_key => :outlet_id, :foreign_key => :id
  has_one :issue_status, :primary_key => :status, :foreign_key => :id
  has_many :issue_comments
end

app/models/issue_comment.rb
class IssueComment < ApplicationRecord
  has_one :user, :primary_key => :user_id, :foreign_key => :id
  has_one :issue

  validates :text, :presence=> true
end

app/models/issue_status.rb
class IssueStatus < ApplicationRecord
end

app/models/outlet.rb
class Outlet < ApplicationRecord
  has_many :users, :through => :outlet_users
  validates :name, :presence=> true
end

app/models/outlet_user.rb
class OutletUser < ApplicationRecord

  belongs_to :user
  belongs_to :outlet
end

app/models/sample.rb
class Sample < ApplicationRecord
  validates :text, :presence=> true
  has_one :outlet, :primary_key => :outlet_id, :foreign_key => :id
  has_one :sample_status, :primary_key => :status, :foreign_key => :id
end

app/models/sample_status.rb
class SampleStatus < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :presence=> true

  validates :family, :presence=> true

  #before_create :set_not_active

  attr_accessor

  def name=(val)
    self[:name] = val.capitalize
  end
  def surename=(val)
    self[:surename] = val.capitalize
  end
  def family=(val)
    self[:family] = val.capitalize
  end
  def is_admin
    return true if self.admin == 1 #The admin account type
  end



  has_many :issues
  has_many :comments
  has_many :samples
  has_many :outlet_users
  has_many :outlets, :through => :outlet_users
  has_one :city

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def index
  end

  def new
    @comment = current_user.comments.new
  end

  def create
    params.permit!
    @comment = Comment.new(params[:comment])
    @comment.valid?
    @user = current_user
    @user.comments.new(params[:comment])



    if @user.save
      flash[:success] = "Отзыв добавлен!"
      redirect_to "/comments"
    else
      #flash[:error] = @comment.errors.full_messages
      render 'new'
    end
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_admin
    if signed_in? && current_user.admin
      true
    else
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end

  def current_user_full_name
    return "#{current_user.family} #{current_user.name} #{current_user.surename}"
  end
end

app/helpers/balance_helper.rb
module BalanceHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/devise_helper.rb
module DeviseHelper




  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
     <div class="alert alert-error alert-block">
       #{messages}
     </div>
    HTML
    html.html_safe
  end
  end

app/helpers/issue_helper.rb
module IssueHelper
end

app/helpers/outlet_helper.rb
module OutletHelper
end

app/helpers/response_helper.rb
module ResponseHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comment/create.html.erb
<h1>Issue#create</h1>
<p>Find me in app/views/issue/create.html.erb</p>

app/views/comment/edit.html.erb
<h1>Issue#edit</h1>
<p>Find me in app/views/issue/edit.html.erb</p>

app/views/comment/index.html.erb
<% provide(:page_title, 'Добро пожаловать!') %>
<div class="container">

  <div class="row">
    <div class="col-sm-3">
      <%= render 'layouts/nav_pill' %>
    </div>
    <div class="col-sm-9">
      <h4>Мои отзывы</h4>
      <%= link_to('Оставить отзыв', comment_new_path, :class => "btn btn-default btn-sm", :role=>"button") %>



      <ul class="issues">
        <%current_user.comments.each do |c|%>
        <li>
          <span class="date">Дата: <%=c.created_at%></span>

          <span class="pull-right text-info"> <%=c.outlet.try(:name || "") %></span>

          <p><%=c.text%></p>
        </li>

      <%end%>
      </ul>

    </div>

  </div>
</div>
</div>

app/views/comment/new.html.erb
<% provide(:page_title, 'Точка продажи') %>
<div class="container">

  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">

        <li><a class="bg-info" href="/">Назад</a></li>

      </ul>

    </div>
    <div class="col-sm-6">
      <h3>Оставить отзыв</h3>

      <%= form_for @comment, :html => {:multipart => true}, :url => comment_create_path do |f| %>
          <% if @comment.errors.any? %>
              <div class="alert alert-warning">
                <% @comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </div>
          <% end %>


          <div class="field">
            <%= f.label 'Точка продаж' %><br>
            <%= f.select :outlet_id, options_for_select(current_user.outlets.map{ |c| [c.name, c.id, ] }) %>
          </div>
          <div class="field">

            <%= f.label 'Отзыв' %>
            <%= f.text_area :text, class: 'form-control'%>
          </div>

          <br>


          <p><%= f.submit "Создать",  :class => "btn btn-primary" %></p>
      <% end %>


    </div>
  </div>
</div>

app/views/comment/show.html.erb
<% provide(:page_title, 'Добро пожаловать!') %>
<div class="container">

  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">

        <li><a href="/balance">Бонусный счёт</a></li>
        <li><a href="/">Профиль</a></li>
        <li><a href="#">Акции</a></li>
        <li><a href="#">Новинки</a></li>
        <li><a href="#">Заказать образцы</a></li>
        <li><a href="#">Отзывы</a></li>
        <li class="active"><a href="/issues">Задать вопрос</a></li>
        <li><a href="#">Вебинары</a></li>

        <li><a href="#">Информация</a></li>

      </ul>
    </div>
    <div class="col-sm-9">


      <ul class="issues">

        <li>
          <span class="date">Дата: <%= @issue.created_at %></span>
          <span class="comments">Комментарии (3)</span>
          Статус:
          <span class="<%= @issue.issue_status.try(:color || "") %>"><%= @issue.issue_status.try(:name || "") %></span>
          <span class="pull-right text-info"> <%= @issue.outlet.try(:name || "") %></span>

          <h4><%= @issue.title %></h4>
          <p><%= @issue.text %></p>
          <h5>Комментарии</h5>
          <ul class="issues">
            <% @issue.issue_comments.each do |c| %>

                <li>
                  <span class="date">Дата: <%= c.created_at %></span>
                  <span class="comments">
                <%= c.user.try(:email || "") %></span>
                  <p><%= c.text %></p>
                </li>
            <% end %>

            <li>
              <%= form_for @issue_comment, :html => {:multipart => true}, :url => issue_add_path do |f| %>

                      <div class="field">

                        <%= f.label 'Ответ' %>
                        <%= f.text_area :text, class: 'form-control' %>
                        <%= f.hidden_field :issue_id, :input_html => {:value => @issue.id} %>
                      </div>




              <br>


              <p><%= f.submit "Создать", :class => "btn btn-primary" %></p>


              <% end %>
      </li>

      </ul>
      </li>

      </ul>


      </div>

</div>
</div>
</div>