config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'

  }


  get 'sample/index'

  get 'sample/create'

  get 'sample/new'

  get 'issue_comment/index'

  get 'issue_comment/edit'

  get 'issue_comment/create'

  get 'issue_comment/add'

  get 'issue/index'

  get 'issue/create'

  get 'issue/new'

  get 'issue/edit'

  get 'outlet/index'

  get 'outlet/new'


  post 'outlet/create'

  get 'outlet/destroy'

  get 'outlet/edit'

  get 'balance/index'
  get 'balance', to: 'balance#index'
  get 'issues', to: 'issue#index'
  get 'issue/:id', to: 'issue#show'
  get 'comments', to: 'comment#index'
  get 'comment/new'
  get 'comment/create'
  post 'comment/create', to: 'comment#create'
  get 'samples', to: 'sample#index'
  post 'sample/create', to: 'sample#create'

  post 'issue/create', to: 'issue#create'
  post 'issue/add', to: 'issue#add'

  get 'balance/create'

  get 'balance/new'

  namespace :admin do
    get 'client/new'
  end

  namespace :admin do
    get 'client/show'
  end

  namespace :admin do
    get 'client/create'
  end

  namespace :admin do
    get 'client/update'
  end

  namespace :admin do
    get 'client/edit'
  end

  namespace :admin do
    get 'client/index'
  end



  root 'static#index'

  get 'static/index'

  get 'static/about'

  get 'static/contact'

  resource :cities
  namespace :admin do
    root 'static#index'

    get 'clients', to: 'client#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one :outlet, :primary_key => :outlet_id, :foreign_key => :id
  validates :text, :presence=> true
end

app/models/issue.rb
class Issue < ApplicationRecord

  validates :title, :presence=> true
  validates :text, :presence=> true
  has_one :outlet, :primary_key => :outlet_id, :foreign_key => :id
  has_one :issue_status, :primary_key => :status, :foreign_key => :id
  has_many :issue_comments
end

app/models/issue_comment.rb
class IssueComment < ApplicationRecord
  has_one :user, :primary_key => :user_id, :foreign_key => :id
  has_one :issue

  validates :text, :presence=> true
end

app/models/issue_status.rb
class IssueStatus < ApplicationRecord
end

app/models/outlet.rb
class Outlet < ApplicationRecord
  has_many :users, :through => :outlet_users
  validates :name, :presence=> true
end

app/models/outlet_user.rb
class OutletUser < ApplicationRecord

  belongs_to :user
  belongs_to :outlet
end

app/models/sample.rb
class Sample < ApplicationRecord
  validates :text, :presence=> true
  has_one :outlet, :primary_key => :outlet_id, :foreign_key => :id
  has_one :sample_status, :primary_key => :status, :foreign_key => :id
end

app/models/sample_status.rb
class SampleStatus < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :presence=> true

  validates :family, :presence=> true

  #before_create :set_not_active

  attr_accessor

  def name=(val)
    self[:name] = val.capitalize
  end
  def surename=(val)
    self[:surename] = val.capitalize
  end
  def family=(val)
    self[:family] = val.capitalize
  end
  def is_admin
    return true if self.admin == 1 #The admin account type
  end



  has_many :issues
  has_many :comments
  has_many :samples
  has_many :outlet_users
  has_many :outlets, :through => :outlet_users
  has_one :city

end

app/controllers/issue_controller.rb
class IssueController < ApplicationController
  def index
  end

  def new
    @issue = current_user.issues.new
  end

  def create
    params.permit!
    @issue = Issue.new(params[:issue])
    @issue.valid?
    @user = current_user
    @user.issues.new(params[:issue])



    if @user.save
      flash[:success] = "Спасибо за Ваш вопрос! Мы ответим на него в ближайшее время!"
      redirect_to "/issues"
    else
      #flash[:error] = @issue.errors.full_messages
      render 'new'
    end
  end

  def edit
  end


  def show
    @issue_comment = IssueComment.new(:issue_id => params[:id], :user_id => current_user.id)
    @issue = Issue.find(params[:id])
  end
  def add
    params.permit!
    @issue_comment = IssueComment.new(params[:issue_comment])
    @issue_comment.user_id = current_user.id

    if @issue_comment.save
      flash[:success] = "Ответ добавлен! "
      redirect_to "/issue/"+params[:issue_comment][:issue_id].to_s
    else
     # flash[:error] = @issue_comment.errors.full_messages
      @issue = Issue.find(params[:issue_comment][:issue_id])

      render "issue/show"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_admin
    if signed_in? && current_user.admin
      true
    else
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end

  def current_user_full_name
    return "#{current_user.family} #{current_user.name} #{current_user.surename}"
  end
end

app/helpers/balance_helper.rb
module BalanceHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/devise_helper.rb
module DeviseHelper




  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
     <div class="alert alert-error alert-block">
       #{messages}
     </div>
    HTML
    html.html_safe
  end
  end

app/helpers/issue_helper.rb
module IssueHelper
end

app/helpers/outlet_helper.rb
module OutletHelper
end

app/helpers/response_helper.rb
module ResponseHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issue/index.html.erb
<% provide(:page_title, 'Добро пожаловать!') %>
<div class="container">

  <div class="row">
    <div class="col-sm-3">
      <%= render 'layouts/nav_pill' %>
    </div>
    <div class="col-sm-9">
      <h4>Мои вопросы</h4>
      <%= link_to('Задать вопрос', issue_new_path, :class => "btn btn-default btn-sm", :role=>"button") %>



      <ul class="issues">
        <%current_user.issues.each do |issue|%>
        <li>
          <span class="date">Дата: <%=issue.created_at%></span>
          <span class="comments">Комментарии (<%= issue.issue_comments.count %>)</span>
          Статус: <span class="<%=issue.issue_status.try(:color || "") %>"><%=issue.issue_status.try(:name || "") %></span>
          <span class="pull-right text-info"> <%=issue.outlet.try(:name || "") %></span>

          <h5><a href="issue/<%=issue.id%>"><%=issue.title%></a></h5>
        </li>

      <%end%>
      </ul>

    </div>

  </div>
</div>
</div>

app/views/issue/new.html.erb
<% provide(:page_title, 'Точка продажи') %>
<div class="container">

  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">

        <li><a href="/">Назад</a></li>

      </ul>

    </div>
    <div class="col-sm-6">
      <h3>Задать вопрос</h3>

      <%= form_for @issue, :html => {:multipart => true}, :url => issue_create_path do |f| %>
          <% if @issue.errors.any? %>
              <div class="alert alert-warning">
                <% @issue.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </div>
          <% end %>

          <div class="field">
            <%= f.label 'Тема вопроса' %>
            <%= f.text_field :title, class: 'form-control'%>
          </div>

          <div class="field">
            <%= f.label 'Точка продаж' %><br>
            <%= f.select :outlet_id, options_for_select(current_user.outlets.map{ |c| [c.name, c.id, ] }) %>
          </div>
          <div class="field">

            <%= f.label 'Вопрос' %>
            <%= f.text_area :text, class: 'form-control'%>
          </div>

          <br>


          <p><%= f.submit "Создать",  :class => "btn btn-primary" %></p>
      <% end %>


    </div>
  </div>
</div>